# Form implementation generated from reading ui file 'qt_project/settingswindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(600, 800)
        font = QtGui.QFont()
        font.setPointSize(10)
        SettingsWindow.setFont(font)
        SettingsWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.defaultButton = QtWidgets.QPushButton(parent=SettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultButton.sizePolicy().hasHeightForWidth())
        self.defaultButton.setSizePolicy(sizePolicy)
        self.defaultButton.setObjectName("defaultButton")
        self.verticalLayout.addWidget(self.defaultButton)
        self.settingsView = QtWidgets.QTreeView(parent=SettingsWindow)
        self.settingsView.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.settingsView.setObjectName("settingsView")
        self.verticalLayout.addWidget(self.settingsView)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SettingsWindow)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsWindow)
        self.buttonBox.accepted.connect(SettingsWindow.accept) # type: ignore
        self.buttonBox.rejected.connect(SettingsWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Dialog"))
        self.defaultButton.setText(_translate("SettingsWindow", "Reset to Default"))
